### ISSUE TITLE
Telegram channels are still mentioned on the main page

### ISSUE THREAD

**Issue by vvv** [KyivHaskell/KyivHaskell#1]
@k-bx [wrote](https://k-bx.github.io/articles/Kyiv-Elm-Study-Group-Experience-Report.html):
> Community-wise, I decided to start with Telegram channel instead of Slack to have a more accessible entrance, especially for JS devs which reside on other Telegram channels. This turned out to be a bad idea. Slack, having its "#random" room for off-topic conversations, would be a much better choice, and we migrated there as soon as the course started.

If we are serious about ditching Telegram channels, the [main page](https://github.com/KyivHaskell/KyivHaskell) should not advertise them.

**Comment by k-bx** [comment]
I'm fine with Telegram for community, just not for the study group.

**Comment by vvv** [comment]
OK.
